### ISSUE TITLE
NSFW

### ISSUE THREAD

**Issue by sha5b** [nateraw/stable-diffusion-videos#102]
"Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed."

I get it all the time in between steps. is there a possibility to tune it down? The black frames between the animation get annoying

**Comment by ZeroCool940711** [comment]
You can disable the safety checker filter, just pass the `safety_checker=None,` argument when loading the model and it should remove the filter, you will get a message about it saying that it is not recommended to disable or something similar but you can ignore it, would be nice if we didn't get any warning at all as we should have the right to completely opt out of it tho but even if the warning is removed from this repo and library diffusers still shows something about it anyway.

**Comment by sha5b** [comment]
Cool, thx for the quick answer!

**Comment by nateraw** [comment]
Thank you @ZeroCool940711 ! Theres an example [here](https://github.com/nateraw/stable-diffusion-videos/blob/main/examples/run_app.py) that shows how to remove safety checker.
