### ISSUE TITLE
add ability to incorporate negative prompts in walk fn

### ISSUE THREAD

**Issue by nateraw** [nateraw/stable-diffusion-videos#114]
Issue brought up [here](https://github.com/nateraw/stable-diffusion-videos/issues/113#issuecomment-1312226158). Negative prompts already available in `__call__` fn but should be surfaced up to `walk`. Not sure if you'd want these to be static or also interpolating...

@xtagon We can continue discussion here, would love your thoughts.

**Comment by xtagon** [comment]
Wow thank you for the quick response! I'm interested in using it for the video interpolation. Would love to be able to set multiple negative prompts, to avoid nsfw and text/signatures.

**Comment by xtagon** [comment]
Hmm, thinking about htis more, I don't think the negative prompts really have to interpolate themselves. I think each frame should just be able to incorporate the negative prompt, and the main prompt itself should interpolate.

**Comment by nateraw** [comment]
If that's the case, I just gave it a go...here's a hack for now. I don't think I'll get to this for a little while so you may just wanna use the solution [here](https://gist.github.com/nateraw/07d32b391efa256395a8504afdaaa0f9).

Would love if you report back that certain negative prompts indeed avoid NSFW content! Would be curious to see examples

**Comment by xtagon** [comment]
Thanks, I'm using it locally instead of in Colab but I don't mind waiting for whenever you get around to it. Thanks again for your help!

**Comment by evenwestvang** [comment]
Also happy to wait 👍 - in the interim I'll be trying to thread the example through the local library

**Comment by nateraw** [comment]
This has been added in the latest version of the package! Should work in walk by providing a `negative_prompt` string arg.
