### ISSUE TITLE
add frame number while running

### ISSUE THREAD

**Issue by lolzemeister** [nateraw/stable-diffusion-videos#116]
![image](https://user-images.githubusercontent.com/102780283/202596811-08522f7a-7d1e-4ace-8d0d-491b474c189d.png)
As you can see in this example, it's very hard to tell where I actually am in the total completion of the video. It would be helpful to have the frame number somewhere here so I can see how close the video actually is to completion. Sorry if this is already included somewhere.

**Comment by nateraw** [comment]
Perhaps just a more descriptive progress bar is needed that'll show 100% as the completion of the video. We'd disable the one is the call function and use our own. I will look into it.
