### ISSUE TITLE
Segmentation Fault when running run_app.py on GPU-backed Ubuntu server

### ISSUE THREAD

**Issue by eolszewski** [nateraw/stable-diffusion-videos#117]
Was going to submit a PR to support a newer version of diffusers but got the following after cloning, pip3 installing, and attempting to run.

`eolszewski@sdtest-2:~/stable-diffusion-videos/examples$ python3 run_app.py`
`Segmentation fault`

I have the package on the same server and working fine. Not sure what the issue might be...

**Comment by nateraw** [comment]
Any more logs available? did you run out of memory by chance?

**Comment by eolszewski** [comment]
Nothing more than `Segmentation fault`

I did see that it crashes on this import `from stable_diffusion_videos import StableDiffusionWalkPipeline, Interface`

This looks like it might be a local issue of sorts, hopefully I can resolve it soon and anyone who gets `Segmentation Fault` in the future will be able to use this as a resource (this is me asking you to not close this, just yet!).

**Comment by nateraw** [comment]
Any update here?

**Comment by eolszewski** [comment]
Sorry, yes, I don't remember the finer details but I was having issues with GCP instances failing to run the nvidia installer on boot if they were created with a machine image (even on machine restart), so, I had to find these scripts and run them manually. This and a number of other issues caused me to move off GCP to lambdalabs (much cheaper!) and I no longer had this issue. So, I don't recall exactly what was happening, but I imagine it to having been a combination of a few niche issues with Google's platform.
