### ISSUE TITLE
cannot load stable_diffusion_videos.stable_diffusion_pipeline.StableDiffusionWalkPipeline

### ISSUE THREAD

**Issue by alexandermolyneux** [nateraw/stable-diffusion-videos#118]
The component <class 'transformers.models.clip.image_processing_clip.CLIPImageProcessor'> of <class 'stable_diffusion_videos.stable_diffusion_pipeline.StableDiffusionWalkPipeline'> cannot be loaded as it does not seem to have any of the loading methods defined in {'ModelMixin': ['save_pretrained', 'from_pretrained'], 'SchedulerMixin': ['save_config', 'from_config'], 'DiffusionPipeline': ['save_pretrained', 'from_pretrained'], 'OnnxRuntimeModel': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizer': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizerFast': ['save_pretrained', 'from_pretrained'], 'PreTrainedModel': ['save_pretrained', 'from_pretrained'], 'FeatureExtractionMixin': ['save_pretrained', 'from_pretrained']}.

**Comment by nateraw** [comment]
What version of diffusers are you using?

**Comment by nateraw** [comment]
I'm guessing this will be fixed if I update diffusers version as well as its underlying transformers install. Will do that this week sometime!!

**Comment by nateraw** [comment]
This should be resolved now - let me know if you run into any other issues
