### ISSUE TITLE
ValueError in the step "Load the Interface"

### ISSUE THREAD

**Issue by fvaldes0109** [nateraw/stable-diffusion-videos#119]
While following the exact steps in the Colab, I keep getting this error when I run Run the App/Load the Interface:

> ValueError: The component <class 'transformers.models.clip.image_processing_clip.CLIPImageProcessor'> of <class 'stable_diffusion_videos.stable_diffusion_pipeline.StableDiffusionWalkPipeline'> cannot be loaded as it does not seem to have any of the loading methods defined in {'ModelMixin': ['save_pretrained', 'from_pretrained'], 'SchedulerMixin': ['save_config', 'from_config'], 'DiffusionPipeline': ['save_pretrained', 'from_pretrained'], 'OnnxRuntimeModel': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizer': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizerFast': ['save_pretrained', 'from_pretrained'], 'PreTrainedModel': ['save_pretrained', 'from_pretrained'], 'FeatureExtractionMixin': ['save_pretrained', 'from_pretrained']}.

**Comment by a-torrano-m** [comment]
Hi,
I am facing the same issue. I thought I had some problem about version mismatch. I saw it was running on version 0.6.2. I wanted to check with 0.6.1. But same exception. I have found people having some similar problem : https://github.com/huggingface/diffusers/issues/1188

I tried to apply one of the solutions, to install transformers directly from git. It did not worked. The other solution was to follow NielsRogge advice (see his quote) : "For me it runs fine, see also the code in app.py of this Space: https://huggingface.co/spaces/nielsr/text-based-inpainting"
But it implies to get inside stable-diffusion-videos library and tinker with the code which I do not own, and wanted to research some advice before-hand.

   Thanks a lot.

Alexis

pd: just stumbled two minutes ago with link I share below. Anyway, I'll keep sharing my message about the issue
https://github.com/nateraw/stable-diffusion-videos/issues/118
