### ISSUE TITLE
error using stable diffusion 2

### ISSUE THREAD

**Issue by omidreza-amrollahi** [nateraw/stable-diffusion-videos#124]
Hi, I get an error as below when I try to use stable diffusion 2:

[/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    672         elif len(missing_modules) > 0:
    673             passed_modules = set(list(init_kwargs.keys()) + list(passed_class_obj.keys())) - optional_kwargs
--> 674             raise ValueError(
    675                 f"Pipeline {pipeline_class} expected {expected_modules}, but only {passed_modules} were passed."
    676             )

ValueError: Pipeline <class 'stable_diffusion_videos.stable_diffusion_pipeline.StableDiffusionWalkPipeline'> expected {'safety_checker', 'vae', 'tokenizer', 'unet', 'text_encoder', 'feature_extractor', 'scheduler'}, but only {'vae', 'tokenizer', 'unet', 'text_encoder', 'scheduler'} were passed.

any ideas how it can be solved? Thanks

**Comment by omidreza-amrollahi** [comment]
works! thank you very much. Is there also a way to create videos between two custom images? (rather than images generated by stable diffusion)

**Comment by nateraw** [comment]
Nope it only works for images generated from the model. You can read a detailed explanation of the logic [here in the music videos post](https://aiart.dev) to understand why that is.
