### ISSUE TITLE
RuntimeError: "lerp_kernel_scalar" not implemented for 'Half'

### ISSUE THREAD

**Issue by nitishalodia** [nateraw/stable-diffusion-videos#125]
Using this on mac m1 machine and getting this error - 
RuntimeError: "lerp_kernel_scalar" not implemented for 'Half'

**Comment by nateraw** [comment]
Can you please provide a full stack trace as a snippet here? (preferably formatted with backticks so I can read it). 

Also any other information about what function you called, etc.

**Comment by nateraw** [comment]
Pinging this issue since its gone stale

**Comment by Atomic-Germ** [comment]
```
$ PYTORCH_ENABLE_MPS_FALLBACK=1 python3 makeVid.py

Fetching 16 files: 100%|█████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 12091.69it/s]
Traceback (most recent call last):
  File "/Users/caseker/Projects/Code/makeVid.py", line 10, in <module>
    video_path = pipeline.walk(
  File "/Users/caseker/Projects/Code/stable-diffusion-videos/stable_diffusion_videos/stable_diffusion_pipeline.py", line 840, in walk
    self.make_clip_frames(
  File "/Users/caseker/Projects/Code/stable-diffusion-videos/stable_diffusion_videos/stable_diffusion_pipeline.py", line 623, in make_clip_frames
    for _, embeds_batch, noise_batch in batch_generator:
  File "/Users/caseker/Projects/Code/stable-diffusion-videos/stable_diffusion_videos/stable_diffusion_pipeline.py", line 562, in generate_inputs
    embeds = torch.lerp(embeds_a, embeds_b, t)
RuntimeError: "lerp_kernel_scalar" not implemented for 'Half'
```

The same thing when I don't use PYTORCH_ENABLE_MPS_FALLBACK=1.

**Comment by nateraw** [comment]
same issue on latest version of code? `pip install --upgrade stable-diffusion-videos`

**Comment by Atomic-Germ** [comment]
It still happens, although the error is a bit prettier now. I'm thinking torch on m1 is missing a few screws.

<img width="725" alt="Screenshot 2023-01-20 at 2 31 55 PM" src="https://user-images.githubusercontent.com/97569476/213817009-c484f6eb-9ec9-4c38-810f-cd91e08338d1.png">

**Comment by nateraw** [comment]
hmm, I wonder if #144 fixes this issue...

could try it yourself...

`pip install git+https://github.com/seriousran/stable-diffusion-videos`

**Comment by Atomic-Germ** [comment]
No, it doesn't seem so. I'm having trouble even figuring out what Half it's referring to in this situation. I'll poke around in it and see if anything makes sense.

**Comment by nateraw** [comment]
Ahh I didn't even think about that - it definitely won't work with half precision, I didn't realize you were using `torch.float16` before. So this is resolved, eh? as I think this is the expected behavior on mps. 

We should add some info to the readme about this probably (Will include when doing #146 )

**Comment by Atomic-Germ** [comment]
It's as resolved as it can be, anyway! A real solution will have to come from Apple at this point, I think. It's alright though, I think adding it to the readme should be good.
