### ISSUE TITLE
Custom image interpolation

### ISSUE THREAD

**Issue by hazcoper** [nateraw/stable-diffusion-videos#142]
Is it possible to use a custom image (not generated) as a starting and ending points to interpolate between them?

**Comment by nateraw** [comment]
Nope they have to be generated. Check out the blog post at aiart.dev to understand more about what's going on here, which should clarify why it's not possible to use your own non generated images

**Comment by Atomic-Germ** [comment]
There are models capable of this kind of thing, I think, but this is definitely not one of them!
