### ISSUE TITLE
import generate_images error

### ISSUE THREAD

**Issue by zencodess** [nateraw/stable-diffusion-videos#209]
When I just try to run the notebook, 
I get the below error while importing Interface.. 

Could you please help?
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-11-5f13c61bb5c8>](https://localhost:8080/#) in <cell line: 3>()
      1 import torch
      2 
----> 3 from stable_diffusion_videos import Interface
      4 from stable_diffusion_videos import StableDiffusionWalkPipeline
      5 

2 frames
[/usr/local/lib/python3.10/dist-packages/stable_diffusion_videos/__init__.py](https://localhost:8080/#) in __getattr__(name)
     73         elif name in attr_to_modules:
     74             submod_path = f"{package_name}.{attr_to_modules[name]}"
---> 75             submod = importlib.import_module(submod_path)
     76             attr = getattr(submod, name)
     77 

[/usr/lib/python3.10/importlib/__init__.py](https://localhost:8080/#) in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

[/usr/local/lib/python3.10/dist-packages/stable_diffusion_videos/app.py](https://localhost:8080/#) in <module>
      3 import gradio as gr
      4 
----> 5 from stable_diffusion_videos import generate_images
      6 
      7 

ImportError: cannot import name 'generate_images' from 'stable_diffusion_videos' (/usr/local/lib/python3.10/dist-packages/stable_diffusion_videos/__init__.py)

**Comment by nateraw** [comment]
Oh hmm I thought I fixed this recently. I'll have a look when I get a chance sorry about that. Thanks for reporting ❤️

**Comment by nateraw** [comment]
Just got around to looking at this. Seems its because package failed to publish to PyPi upon release. Didn't notice that. 
 @Borda any chance this has something to do with changes you had made?

See this failed action: https://github.com/nateraw/stable-diffusion-videos/actions/runs/8979155015/job/24660699159

**Comment by nateraw** [comment]
ah actually could be an authentication issue? I believe I was using username + pass before, perhaps they've changed something and you have to use API keys now?

**Comment by Borda** [comment]
Yes authentication...

**Comment by nateraw** [comment]
issue fixed on main still haven't had time to fix pypi auth

**Comment by LukeLIN-web** [comment]
issue fixed on main still haven't had time to fix pypi auth. I think we need install from git repo.

**Comment by nateraw** [comment]
main branch works fine right now, but haven't shipped to PyPi :/ . Happy to do that but authentication to PyPi has changed and I haven't found time to fix it yet.  😢 

@LukeLIN-web that import should work just fine if you installed main branch. Check the [colab](https://colab.research.google.com/github/nateraw/stable-diffusion-videos/blob/main/stable_diffusion_videos.ipynb) from the README - it works I just tried it.

**Comment by nateraw** [comment]
Ok this should be resolved now, finally got around to pypi publish. 0.9.1 on pypi works :)
