### ISSUE TITLE
Allow users to pass in a specified StableDiffusionPipeline

### ISSUE THREAD

**Issue by minimaxir** [nateraw/stable-diffusion-videos#25]
In `stable_diffusion_walk.py`, the StableDiffusionPipeline is hardcoded at `v1.4` and `fp16`.

https://github.com/nateraw/stable-diffusion-videos/blob/8a7b3b0533aaf1bcb4eb89714bf606746f60535b/stable_diffusion_videos/stable_diffusion_walk.py#L13-L18

The `walk()` function should take in a parametric StableDiffusionPipeline because a) there may be other/better StableDiffusion models in the future and b) if the text tokenizer of the Pipeline needs to be augmeneted in order to generate from textual inversion-trained embeddings.

**Comment by nateraw** [comment]
#28 proposes the pipeline solution. 

btw, not against just doing what you suggest here and throwing the pipeline idea away, so feel free to weigh in :) I appreciate your contribution here.

**Comment by nateraw** [comment]
I ended up going with the pipeline option. So this is closed now, as this feature is effectively done.
