### ISSUE TITLE
 ImportError: cannot import name 'PipelineRealESRGAN' from 'stable_diffusion_videos'

### ISSUE THREAD

**Issue by 0x1355** [nateraw/stable-diffusion-videos#30]
Hey there, 

Awesome feature and quality code! Thanks!

Everything works for me except for upsampling. Whenever I added `upsample=True` in walk(), I got:

> ImportError: cannot import name 'PipelineRealESRGAN' from 'stable_diffusion_videos' (/home/env/lib/python3.8/site-packages/stable_diffusion_videos/__init__.py)

Any thought on how to solve this? Thanks

**Comment by nateraw** [comment]
Hey there! Did you install `realesrgan`? You have two options:

I added it as a package extra here, so you can do this (as I do in the colab from the readme)

```
pip install --upgrade stable_diffusion_videos[realesrgan]
```

or just install it directly from pypi

```
pip install realesrgan
```

If you did, please share the full error log or (even better) a way for me to reproduce the error in Google Colab.

**Comment by 0x1355** [comment]
Aha. I installed it into the wrong environment. Thanks for helping me solve this!

BTW, I also got an `AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)` after installing realesrgan. Solved that by `pip install "opencv-python-headless<4.3"`
