### ISSUE TITLE
NameError: name 'interface' is not defined

### ISSUE THREAD

**Issue by Aitrepreneur** [nateraw/stable-diffusion-videos#40]
Hey there, I get this error when trying to run the interface.launch(debug=True) cell on the Colab Doc:

```
NameError                                 Traceback (most recent call last)
[<ipython-input-4-75e4cf6bcc7d>](https://localhost:8080/#) in <module>
----> 1 interface.launch(debug=True)

NameError: name 'interface' is not defined
```

Any solutions for this? Thank you :)

**Comment by nateraw** [comment]
You have to make sure you run all the cells, including the hugging face login step. Interface won't be defined if you didn't run those - specifically the one that says `from stable_diffusion_videos import interface`.

Closing this, as I just ran it and it was fine. Let me know if for some reason your issue persists after following the directions above.

**Comment by Aitrepreneur** [comment]
> 
Hey there, yes now it works for some reason, just tested it myself. Thank you ;)
