### ISSUE TITLE
add num steps for each prompt

### ISSUE THREAD

**Issue by danielpatrickhug** [nateraw/stable-diffusion-videos#41]
I was thinking it would be useful to allow for some prompts to run longer than others. so changing num_steps from an int to a list of ints.
essentially changing 
```python
for prompt, seed in zip(prompts, seeds):
```
to 
```python
for prompt, seed, num_step in zip(prompts, seeds, num_steps):
```
What do you think?
potentially expand this to all parameters by using parameter dict for each prompt.

**Comment by nateraw** [comment]
Interesting idea here. Will look into this!

**Comment by danielpatrickhug** [comment]
I can make a pull request.

**Comment by nateraw** [comment]
That would be great, @danielpatrickhug ! Do you mind waiting until we sort out #35 ? Otherwise I worry there will be a bit of a mess with conflicts. 

We'll want to make sure this feature saves these differing seeds to prompt config, and supports resuming.

**Comment by danielpatrickhug** [comment]
of course! no rush.

**Comment by danielpatrickhug** [comment]
one idea that could be cool would be to pass in a list of Scene objects 
to represent the dag walk and interpolate between the scene objects.
``` python
scene = Scene(prompt:str, seed:int, num_steps:int, height:int,
                    width:int,
                    guidance_scale:float,
                    eta:float,
                    num_inference_steps:int,...)
```
potentially pass in a scene_type too,  like txt2img, img2img

**Comment by nateraw** [comment]
Interesting idea here...could potentially be nice to store things in a more structured object like this and create dags that could then be edited/resumed down the line.

I would lean against implementing something like that for now (probably next month or so), as it may lead to unnecessary complexity while we iterate on other ideas - but lets not throw that thought away. Might be more applicable down the line as more work shapes up here. If you want to discuss more, feel free to open separate issue for that so we keep issues focused on one topic at a time 😄 .

**Comment by danielpatrickhug** [comment]
sure, thinking, for #35 we can save the individual prompt configs as records in prompt_config.json, moving it under the first for loop saving at each outer iteration. a reset could look at the number of frames and map the index to the json record that it ended at and then restarts from there i.e modify the outer iteration index to start from where it ended.

**Comment by nateraw** [comment]
So the continuing stuff has been merged. Could add "num_steps as list" feature now. If its an int, I suppose you could turn it to a list like `num_steps = [num_steps] * (len(prompts) - 1)`, or otherwise use it as expected. Would need to check the length is as expected as well. 

This info should be saved in prompt config so it can be loaded back when `resume=True`.

**Comment by danielpatrickhug** [comment]
sure. we can add a check in that case that an int is passed in. so that it doesn't break existing code.
```python
if isinstance(num_steps, int):
    num_steps = [num_steps] * (len(prompts) - 1)
```
```
I don't think we have to make any changes to the prompt_config, it should save and load the list like prompts and seeds.
So then it is just a matter of updating the outer iteration to zip through the num steps list and update the inner iteration to use the new num_steps vars.

**Comment by danielpatrickhug** [comment]
I added typing too, if you dont want that or want to seperate that change into a different pull request lmk I'll make the change.
