### ISSUE TITLE
Determine if best default is lerp or slerp for text embeddings

### ISSUE THREAD

**Issue by nateraw** [nateraw/stable-diffusion-videos#46]
The `use_lerp_for_text` param lets you use lerp instead of slerp for text embedding interpolation. There was [a comment](https://gist.github.com/nateraw/c989468b74c616ebbc6474aa8cdd9e53?permalink_comment_id=4282841#gistcomment-4282841) on my original gist suggesting lerp was better, but I never got around to doing exhaustive comparison. 

Would be nice if we could do this + set the value (or even get rid of the option to change it) based on what's best.

**Comment by nateraw** [comment]
@0x1355 have you experimented with this by any chance?

**Comment by 0x1355** [comment]
Not yet but it is now priority one on my experiment board. Will let you know soon.

**Comment by 0x1355** [comment]
Experiment done. Writing up. Taking longer because I are changing something in my pipeline. Will share result tomorrow 🔆

**Comment by nateraw** [comment]
Thank you!!! Looking forward to it. Also running a few experiments separately

**Comment by 0x1355** [comment]
Putting my thoughts in a thread and tagged some AI artists I followed. Hope we can get everyone to compare notes.

https://twitter.com/DreamLatent/status/1573166763268767744
