### ISSUE TITLE
Is interpolation allowed between two artificially specified images？

### ISSUE THREAD

**Issue by Luffffffy** [nateraw/stable-diffusion-videos#49]
As shown in the title.
Thanks for your fantastic work !!!

**Comment by 0x1355** [comment]
What do you mean by 'artificially specified images'?

**Comment by nateraw** [comment]
I think your question is "can I interpolate between any two images that were not generated with stable diffusion?". If that's the case - then the answer is no...we can only interpolate between stable diffusion generated images.

**Comment by 0x1355** [comment]
@Luffffffy If you are looking for interpolating any two images, [FILM](https://github.com/google-research/frame-interpolation) is the best one I have tried.

**Comment by Luffffffy** [comment]
> I think your question is "can I interpolate between any two images that were not generated with stable diffusion?". If that's the case - then the answer is no...we can only interpolate between stable diffusion generated images.

Sorry for my poor English, but you still understand, thank you for your answer, i got it

**Comment by Luffffffy** [comment]
> @Luffffffy If you are looking for interpolating any two images, [FILM](https://github.com/google-research/frame-interpolation) is the best one I have tried.

Oh, thank you very much, I'll try
