### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by canpoyrazoglu** [nateraw/stable-diffusion-videos#8]
I'm trying to run the notebook. I've ran the setup successfully, I've also logged in successfully with my HF token. When I run  the "Load the interface" cell I get the following ModuleNotFoundError error:
```
/content/stable-diffusion-videos
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-4-fa6e4247984b>](https://h7k0zf9a2wc-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220906-060059-RC00_472423659#) in <module>
      2 get_ipython().run_line_magic('cd', '/content/stable-diffusion-videos/')
      3 
----> 4 from app import interface

ModuleNotFoundError: No module named 'app'
```

**Comment by nateraw** [comment]
You're running it locally? You can do `pip install stable_diffusion_videos`, then simply:

```python
from stable_diffusion_videos import interface

interface.launch()
```

The code is a bit different than it was 24 hours ago - its packaged into python package now. lmk if this solves your issue

**Comment by nateraw** [comment]
I'm also running on Colab pro. Should be workin just fine! But please let me know if the issue persists. Also - please make sure you're using the latest colab which you can access from the readme. The previous version will not work anymore due to the restructure, but the one in the root of the repo works fine.

**Comment by nateraw** [comment]
closing this, as I don't believe its an issue.

**Comment by canpoyrazoglu** [comment]
Sorry for the late reply, had been super-busy.

Just checked, yup I confirm the latest version as of now works perfectly!

Thanks for the great work @nateraw!
